import type { ImageAttachment } from "./messages.ts";

/** Rich payload a tool can hand to the renderer for display purposes. */
export interface ToolDisplay {
  kind: "text" | "diff" | "list" | "none";
  /** Short headline, e.g. "src/net/fetch.ts". */
  title?: string;
  text?: string;
  /** Unified diff, already generated by the tool. */
  diff?: string;
  lines?: string[];
  /** Collapse output beyond this many lines in the transcript. */
  collapseAfter?: number;
  lang?: string;
  addedLines?: number;
  removedLines?: number;
  meta?: Record<string, string>;
}

export interface ToolDisplayResult {
  /** Text handed back to the model. */
  content: string;
  isError?: boolean;
  /** One-line summary for the transcript row, e.g. "128 lines". */
  summary?: string;
  display?: ToolDisplay;
  meta?: ToolResultMeta;
  /** Images handed to the model alongside the text. */
  images?: ImageAttachment[];
}

export interface ToolResultMeta {
  durationMs?: number;
  exitCode?: number;
  bytes?: number;
  readFiles?: string[];
  changedFiles?: string[];
  addedLines?: number;
  removedLines?: number;
  truncated?: boolean;
  /** Suppress the transcript row entirely (used by internal bookkeeping tools). */
  quiet?: boolean;
  /** Marks tool output that may be pruned aggressively during compaction. */
  volatile?: boolean;
}

export function textResult(content: string, meta?: ToolResultMeta): ToolDisplayResult {
  return { content, meta };
}

export function errorResult(content: string, meta?: ToolResultMeta): ToolDisplayResult {
  return { content, isError: true, meta };
}
